# Generated by Django 5.0.1 on 2025-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOOSTER', 'Booster'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
